const hotels = [
  {
    id: '1',
    name: 'Blue Lagoon Resort',
    location: 'Lagoon Avenue, Bali',
    price: 120,
    rating: 4.8,
    reviews: 1247,
    image: require('../assets/hotel1.jpg'),
    details: 'A luxury resort located on a beautiful private beach with tropical gardens and ocean views.',
    amenities: ['Private Beach', 'Infinity Pool', 'Spa & Wellness', 'Free WiFi', 'Restaurant', 'Bar'],
    roomTypes: ['Ocean View Suite', 'Garden Villa', 'Beach Bungalow'],
    checkIn: '3:00 PM',
    checkOut: '11:00 AM',
    distance: '15 min from airport',
    category: 'Beach Resort',
    featured: true,
    gallery: [
      require('../assets/hotel15.jpg'),
      require('../assets/hotel3.jpg'),
      require('../assets/hotel9.jpg')
    ]
  },
  {
    id: '2',
    name: 'Mountain View Inn',
    location: 'Aspen Hills, Colorado',
    price: 95,
    rating: 4.5,
    reviews: 892,
    image: require('../assets/hotel2.jpg'),
    details: 'Enjoy breathtaking mountain views, cozy fireplaces, and ski-in/ski-out access.',
    amenities: ['Ski-in/Ski-out', 'Fireplace', 'Mountain Views', 'Hot Tub', 'Free Parking', 'Pet Friendly'],
    roomTypes: ['Mountain Suite', 'Cozy Cabin', 'Family Lodge'],
    checkIn: '4:00 PM',
    checkOut: '10:00 AM',
    distance: '5 min from ski lifts',
    category: 'Mountain Lodge',
    featured: false,
    gallery: [
      require('../assets/hotel12.jpg'),
      require('../assets/hotel7.jpg'),
      require('../assets/hotel21.jpg')
    ]
  },
  {
    id: '3',
    name: 'Urban Nest Hotel',
    location: 'Downtown Tokyo, Japan',
    price: 135,
    rating: 4.7,
    reviews: 2156,
    image: require('../assets/hotel3.jpg'),
    details: 'Modern hotel in the heart of the city with easy access to shopping, dining, and nightlife.',
    amenities: ['City Center', 'Business Center', 'Rooftop Bar', 'Gym', 'Concierge', '24/7 Room Service'],
    roomTypes: ['Executive Suite', 'Deluxe Room', 'Business Room'],
    checkIn: '3:00 PM',
    checkOut: '12:00 PM',
    distance: '2 min from subway',
    category: 'Business Hotel',
    featured: true,
    gallery: [
      require('../assets/hotel18.jpg'),
      require('../assets/hotel6.jpg'),
      require('../assets/hotel11.jpg')
    ]
  },
  {
    id: '4',
    name: 'Palm Breeze Retreat',
    location: 'Goa Beach, India',
    price: 110,
    rating: 4.3,
    reviews: 756,
    image: require('../assets/hotel4.jpg'),
    details: 'Beachfront retreat with palm trees, cocktails, and colorful sunsets every evening.',
    amenities: ['Beachfront', 'Tiki Bar', 'Water Sports', 'Yoga Classes', 'Beach Volleyball', 'Massage'],
    roomTypes: ['Beach Villa', 'Palm Suite', 'Sunset Room'],
    checkIn: '2:00 PM',
    checkOut: '11:00 AM',
    distance: 'Beachfront location',
    category: 'Beach Resort',
    featured: false,
    gallery: [
      require('../assets/hotel23.jpg'),
      require('../assets/hotel5.jpg'),
      require('../assets/hotel14.jpg')
    ]
  },
  {
    id: '5',
    name: 'Serenity Hills Lodge',
    location: 'Napa Valley, California',
    price: 150,
    rating: 4.9,
    reviews: 1834,
    image: require('../assets/hotel5.jpg'),
    details: 'Exclusive wine country lodge with vineyard views, spa treatments, and gourmet dining.',
    amenities: ['Vineyard Views', 'Wine Tasting', 'Spa', 'Fine Dining', 'Private Balcony', 'Concierge'],
    roomTypes: ['Vineyard Suite', 'Wine Master Room', 'Luxury Villa'],
    checkIn: '4:00 PM',
    checkOut: '11:00 AM',
    distance: '10 min from wineries',
    category: 'Luxury Resort',
    featured: true,
    gallery: [
      require('../assets/hotel1.jpg'),
      require('../assets/hotel17.jpg'),
      require('../assets/hotel8.jpg')
    ]
  },
  {
    id: '6',
    name: 'Skyline Tower Hotel',
    location: 'New York City, NY',
    price: 200,
    rating: 4.6,
    reviews: 3421,
    image: require('../assets/hotel6.jpg'),
    details: 'Stay in the clouds at this skyscraper hotel offering panoramic views of Manhattan.',
    amenities: ['City Views', 'Rooftop Pool', 'Fine Dining', 'Valet Parking', 'Business Center', 'Gym'],
    roomTypes: ['Penthouse Suite', 'City View Room', 'Executive Floor'],
    checkIn: '3:00 PM',
    checkOut: '12:00 PM',
    distance: '5 min from Times Square',
    category: 'Luxury Hotel',
    featured: true,
    gallery: [
      require('../assets/hotel20.jpg'),
      require('../assets/hotel13.jpg'),
      require('../assets/hotel2.jpg')
    ]
  },
  {
    id: '7',
    name: 'Safari Sunset Camp',
    location: 'Masai Mara, Kenya',
    price: 180,
    rating: 4.8,
    reviews: 967,
    image: require('../assets/hotel7.jpg'),
    details: 'Experience the wild in luxury tents with views of the African savanna and wildlife safaris.',
    amenities: ['Safari Tours', 'Luxury Tents', 'Wildlife Viewing', 'Campfire', 'Local Guide', 'All Meals'],
    roomTypes: ['Safari Tent', 'Family Tent', 'Honeymoon Tent'],
    checkIn: '2:00 PM',
    checkOut: '10:00 AM',
    distance: 'Heart of Masai Mara',
    category: 'Safari Lodge',
    featured: true,
    gallery: [
      require('../assets/hotel4.jpg'),
      require('../assets/hotel19.jpg'),
      require('../assets/hotel10.jpg')
    ]
  },
  {
    id: '8',
    name: 'The Ice Palace',
    location: 'Reykjavik, Iceland',
    price: 130,
    rating: 4.2,
    reviews: 543,
    image: require('../assets/hotel8.jpg'),
    details: 'Chill out in a one-of-a-kind ice-themed hotel with geothermal baths and aurora views.',
    amenities: ['Ice Rooms', 'Aurora Views', 'Geothermal Spa', 'Ice Bar', 'Northern Lights Tours', 'Heated Areas'],
    roomTypes: ['Ice Suite', 'Aurora Room', 'Warm Lodge'],
    checkIn: '4:00 PM',
    checkOut: '10:00 AM',
    distance: '20 min from city center',
    category: 'Unique Experience',
    featured: false,
    gallery: [
      require('../assets/hotel16.jpg'),
      require('../assets/hotel22.jpg'),
      require('../assets/hotel9.jpg')
    ]
  },
  {
    id: '9',
    name: 'Zen Garden Hotel',
    location: 'Kyoto, Japan',
    price: 100,
    rating: 4.5,
    reviews: 1289,
    image: require('../assets/hotel9.jpg'),
    details: 'Tranquil stay surrounded by bamboo groves, koi ponds, and peaceful tea houses.',
    amenities: ['Zen Garden', 'Tea Ceremony', 'Meditation Area', 'Traditional Baths', 'Bamboo Forest', 'Koi Pond'],
    roomTypes: ['Traditional Ryokan', 'Garden View', 'Zen Suite'],
    checkIn: '3:00 PM',
    checkOut: '11:00 AM',
    distance: '10 min from temples',
    category: 'Traditional Hotel',
    featured: false,
    gallery: [
      require('../assets/hotel11.jpg'),
      require('../assets/hotel14.jpg'),
      require('../assets/hotel1.jpg')
    ]
  },
  {
    id: '10',
    name: 'Ocean Pearl Resort',
    location: 'Maldives',
    price: 300,
    rating: 5.0,
    reviews: 2847,
    image: require('../assets/hotel10.jpg'),
    details: 'Overwater villas, private pools, and crystal-clear waters for the perfect island escape.',
    amenities: ['Overwater Villa', 'Private Pool', 'Snorkeling', 'Spa', 'Fine Dining', 'Butler Service'],
    roomTypes: ['Water Villa', 'Beach Villa', 'Presidential Suite'],
    checkIn: '2:00 PM',
    checkOut: '12:00 PM',
    distance: 'Private island',
    category: 'Luxury Resort',
    featured: true,
    gallery: [
      require('../assets/hotel6.jpg'),
      require('../assets/hotel15.jpg'),
      require('../assets/hotel3.jpg')
    ]
  },
  {
    id: '11',
    name: 'Savannah Grand',
    location: 'Cape Town, South Africa',
    price: 140,
    rating: 4.6,
    reviews: 1156,
    image: require('../assets/hotel11.jpg'),
    details: 'Elegant rooms, wine tastings, and views of Table Mountain in this coastal retreat.',
    amenities: ['Mountain Views', 'Wine Cellar', 'Ocean Access', 'Fine Dining', 'Spa', 'Tour Desk'],
    roomTypes: ['Mountain View Suite', 'Ocean Room', 'Presidential Villa'],
    checkIn: '3:00 PM',
    checkOut: '11:00 AM',
    distance: '15 min from Table Mountain',
    category: 'Boutique Hotel',
    featured: true,
    gallery: [
      require('../assets/hotel8.jpg'),
      require('../assets/hotel23.jpg'),
      require('../assets/hotel18.jpg')
    ]
  },
  {
    id: '12',
    name: 'Royal Heritage Palace',
    location: 'Jaipur, India',
    price: 115,
    rating: 4.7,
    reviews: 876,
    image: require('../assets/hotel12.jpg'),
    details: 'Live like royalty in this beautifully restored palace with regal rooms and rich history.',
    amenities: ['Palace Architecture', 'Royal Gardens', 'Heritage Tours', 'Traditional Spa', 'Cultural Shows', 'Elephant Rides'],
    roomTypes: ['Royal Suite', 'Heritage Room', 'Palace Wing'],
    checkIn: '2:00 PM',
    checkOut: '12:00 PM',
    distance: '5 min from City Palace',
    category: 'Heritage Hotel',
    featured: true,
    gallery: [
      require('../assets/hotel7.jpg'),
      require('../assets/hotel21.jpg'),
      require('../assets/hotel5.jpg')
    ]
  },
  {
    id: '13',
    name: 'Tropical Bay Villas',
    location: 'Phuket, Thailand',
    price: 160,
    rating: 4.8,
    reviews: 1567,
    image: require('../assets/hotel13.jpg'),
    details: 'Private villas nestled on a cliff overlooking the turquoise bay. A honeymoon favorite.',
    amenities: ['Private Villa', 'Cliff Views', 'Infinity Pool', 'Private Beach', 'Couples Spa', 'Romantic Dining'],
    roomTypes: ['Cliff Villa', 'Bay View Villa', 'Honeymoon Suite'],
    checkIn: '3:00 PM',
    checkOut: '11:00 AM',
    distance: '25 min from airport',
    category: 'Romantic Resort',
    featured: true,
    gallery: [
      require('../assets/hotel2.jpg'),
      require('../assets/hotel16.jpg'),
      require('../assets/hotel12.jpg')
    ]
  },
  {
    id: '14',
    name: 'The Desert Mirage',
    location: 'Dubai, UAE',
    price: 250,
    rating: 4.9,
    reviews: 2934,
    image: require('../assets/hotel14.jpg'),
    details: 'Futuristic design meets Arabian charm in this 7-star experience in the heart of Dubai.',
    amenities: ['7-Star Service', 'Desert Safari', 'Gold Souk Access', 'Helicopter Tours', 'Butler Service', 'Michelin Dining'],
    roomTypes: ['Royal Suite', 'Desert Villa', 'Sky Penthouse'],
    checkIn: '3:00 PM',
    checkOut: '12:00 PM',
    distance: '10 min from Burj Khalifa',
    category: 'Ultra Luxury',
    featured: true,
    gallery: [
      require('../assets/hotel19.jpg'),
      require('../assets/hotel4.jpg'),
      require('../assets/hotel17.jpg')
    ]
  },
  {
    id: '15',
    name: 'Aurora Borealis Lodge',
    location: 'Tromsø, Norway',
    price: 170,
    rating: 4.7,
    reviews: 743,
    image: require('../assets/hotel15.jpg'),
    details: 'Glass-ceiling rooms let you sleep under the Northern Lights in cozy comfort.',
    amenities: ['Glass Ceiling', 'Aurora Alerts', 'Husky Sledding', 'Reindeer Farm', 'Ice Fishing', 'Warm Sauna'],
    roomTypes: ['Aurora Dome', 'Glass Igloo', 'Northern Suite'],
    checkIn: '4:00 PM',
    checkOut: '10:00 AM',
    distance: '30 min from city',
    category: 'Adventure Lodge',
    featured: true,
    gallery: [
      require('../assets/hotel10.jpg'),
      require('../assets/hotel20.jpg'),
      require('../assets/hotel22.jpg')
    ]
  },
  {
    id: '16',
    name: 'Forest Whisper Cabins',
    location: 'Banff, Canada',
    price: 105,
    rating: 4.5,
    reviews: 654,
    image: require('../assets/hotel16.jpg'),
    details: 'Wooden cabins deep in the forest, ideal for a peaceful retreat in nature.',
    amenities: ['Forest Location', 'Hiking Trails', 'Wildlife Viewing', 'Campfire Area', 'Fishing', 'Mountain Biking'],
    roomTypes: ['Forest Cabin', 'Lake View Cabin', 'Family Lodge'],
    checkIn: '3:00 PM',
    checkOut: '11:00 AM',
    distance: '1 hour from Calgary',
    category: 'Nature Retreat',
    featured: false,
    gallery: [
      require('../assets/hotel9.jpg'),
      require('../assets/hotel13.jpg'),
      require('../assets/hotel6.jpg')
    ]
  },
  {
    id: '17',
    name: 'Vintage Vine Inn',
    location: 'Tuscany, Italy',
    price: 145,
    rating: 4.9,
    reviews: 1923,
    image: require('../assets/hotel17.jpg'),
    details: 'Rustic Italian charm meets modern comfort in the heart of vineyard country.',
    amenities: ['Vineyard Tours', 'Wine Tasting', 'Cooking Classes', 'Olive Grove', 'Cycling', 'Art Galleries'],
    roomTypes: ['Vineyard Room', 'Tuscan Suite', 'Villa Apartment'],
    checkIn: '2:00 PM',
    checkOut: '11:00 AM',
    distance: '45 min from Florence',
    category: 'Wine Country',
    featured: true,
    gallery: [
      require('../assets/hotel14.jpg'),
      require('../assets/hotel11.jpg'),
      require('../assets/hotel23.jpg')
    ]
  },
  {
    id: '18',
    name: 'The Pearl Marina',
    location: 'Barcelona, Spain',
    price: 125,
    rating: 4.4,
    reviews: 1087,
    image: require('../assets/hotel18.jpg'),
    details: 'Waterfront elegance with yacht views and sangria sunsets.',
    amenities: ['Marina Views', 'Yacht Charter', 'Rooftop Terrace', 'Tapas Bar', 'Beach Access', 'City Tours'],
    roomTypes: ['Marina Suite', 'Yacht View Room', 'Penthouse'],
    checkIn: '3:00 PM',
    checkOut: '12:00 PM',
    distance: '10 min from Las Ramblas',
    category: 'Marina Hotel',
    featured: false,
    gallery: [
      require('../assets/hotel5.jpg'),
      require('../assets/hotel12.jpg'),
      require('../assets/hotel8.jpg')
    ]
  },
  {
    id: '19',
    name: 'Sunset Breeze Resort',
    location: 'Boracay, Philippines',
    price: 112,
    rating: 4.6,
    reviews: 1432,
    image: require('../assets/hotel19.jpg'),
    details: 'White sands, water sports, and palm trees in paradise.',
    amenities: ['White Beach', 'Water Sports', 'Island Hopping', 'Massage Huts', 'Beach Bar', 'Sunset Cruise'],
    roomTypes: ['Beach Front Room', 'Garden Villa', 'Sunset Suite'],
    checkIn: '2:00 PM',
    checkOut: '11:00 AM',
    distance: 'Direct beach access',
    category: 'Beach Resort',
    featured: true,
    gallery: [
      require('../assets/hotel22.jpg'),
      require('../assets/hotel7.jpg'),
      require('../assets/hotel15.jpg')
    ]
  },
  {
    id: '20',
    name: 'The Nordic Retreat',
    location: 'Helsinki, Finland',
    price: 110,
    rating: 4.3,
    reviews: 698,
    image: require('../assets/hotel20.jpg'),
    details: 'Stylish Nordic design with spa facilities and forest walking trails.',
    amenities: ['Nordic Design', 'Finnish Sauna', 'Forest Trails', 'Spa Treatments', 'Local Cuisine', 'Design Tours'],
    roomTypes: ['Nordic Room', 'Forest Suite', 'Design Loft'],
    checkIn: '3:00 PM',
    checkOut: '11:00 AM',
    distance: '15 min from city center',
    category: 'Design Hotel',
    featured: false,
    gallery: [
      require('../assets/hotel17.jpg'),
      require('../assets/hotel1.jpg'),
      require('../assets/hotel10.jpg')
    ]
  },
  {
    id: '21',
    name: 'Riverstone Lodge',
    location: 'Queenstown, New Zealand',
    price: 135,
    rating: 4.7,
    reviews: 876,
    image: require('../assets/hotel21.jpg'),
    details: 'Nestled between rivers and mountains, perfect for adventure seekers.',
    amenities: ['Adventure Sports', 'River Views', 'Bungee Jumping', 'Skydiving', 'Jet Boating', 'Wine Tours'],
    roomTypes: ['Adventure Suite', 'River Room', 'Mountain Lodge'],
    checkIn: '3:00 PM',
    checkOut: '10:00 AM',
    distance: '5 min from adventure center',
    category: 'Adventure Lodge',
    featured: true,
    gallery: [
      require('../assets/hotel3.jpg'),
      require('../assets/hotel18.jpg'),
      require('../assets/hotel4.jpg')
    ]
  },
  {
    id: '22',
    name: 'Laguna Shores Hotel',
    location: 'Los Angeles, CA',
    price: 150,
    rating: 4.5,
    reviews: 1765,
    image: require('../assets/hotel22.jpg'),
    details: 'Chic California vibes with rooftop pools and beachfront dining.',
    amenities: ['Rooftop Pool', 'Beach Access', 'Celebrity Chef', 'Valet Parking', 'Spa Services', 'Shopping Access'],
    roomTypes: ['Ocean View Suite', 'Poolside Room', 'Celebrity Suite'],
    checkIn: '4:00 PM',
    checkOut: '11:00 AM',
    distance: '10 min from Hollywood',
    category: 'Luxury Beach',
    featured: true,
    gallery: [
      require('../assets/hotel16.jpg'),
      require('../assets/hotel9.jpg'),
      require('../assets/hotel13.jpg')
    ]
  },
  {
    id: '23',
    name: 'Golden Sands Retreat',
    location: 'Cancun, Mexico',
    price: 138,
    rating: 4.6,
    reviews: 2187,
    image: require('../assets/hotel23.jpg'),
    details: 'All-inclusive comfort steps away from turquoise Caribbean beaches.',
    amenities: ['All-Inclusive', 'Private Beach', 'Multiple Pools', 'Water Park', 'Kids Club', 'Nightclub'],
    roomTypes: ['Ocean View Room', 'Family Suite', 'Adults Only Wing'],
    checkIn: '3:00 PM',
    checkOut: '12:00 PM',
    distance: '20 min from airport',
    category: 'All-Inclusive',
    featured: true,
    gallery: [
      require('../assets/hotel21.jpg'),
      require('../assets/hotel2.jpg'),
      require('../assets/hotel19.jpg')
    ]
  },
];

export default hotels;